// <auto-generated />
namespace Dna.Mvp.Data.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class combine_scripts_UpdatePrimaryColumnOnAllDataType_and_many_many_user_roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(combine_scripts_UpdatePrimaryColumnOnAllDataType_and_many_many_user_roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201505210533144_combine_scripts_UpdatePrimaryColumnOnAllDataType_and_many_many_user_roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
