// <auto-generated />
namespace Dna.Mvp.Data.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _20150303A_Initialization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150303A_Initialization));
        
        string IMigrationMetadata.Id
        {
            get { return "201503030423246_20150303A_Initialization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
