// <auto-generated />
namespace Dna.Mvp.Data.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_1n_for_User_Validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_1n_for_User_Validation));
        
        string IMigrationMetadata.Id
        {
            get { return "201505211025207_add_1-n_for_User_Validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
